version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: deepfake_user
      POSTGRES_PASSWORD: deepfake_password
      POSTGRES_DB: deepfake_detector
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deepfake_user -d deepfake_detector"]
      interval: 30s
      timeout: 10s
      retries: 5

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=deepfake_user
      - POSTGRES_PASSWORD=deepfake_password
      - POSTGRES_DB=deepfake_detector
      - ENVIRONMENT=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./model:/app/model

volumes:
  postgres_data:
